"use client";

import CreateRideForm, { type CreateRideFormValues } from "@/components/form/rideForm";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import * as React from "react";
import { toast } from "sonner";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Textarea } from "../ui/textarea";
import type { ClientProfile } from "@/lib/types";

type Client = {
    value: string;
    label: string;
    profile: ClientProfile;
};

export default function CreateRideModal() {
    const [open, setOpen] = React.useState(false);
    const [selectedClientValue, setSelectedClientValue] = React.useState<string>("");

    // Sample client data (to be replaced with API data later)
    // (generated by ai)
    const clients: Client[] = [
        {
            value: "clientOne",
            label: "Bob Joel",
            profile: {
                address: "123 Park Avenue",
                zip: "14607",
                city: "Rochester",
                state: "NY",
                typeOfResidence: "Single Family Home",
                primaryPhone: "(585) 555-1234",
                vehicleTypeNeeded: "Wheelchair Accessible Van",
                oxygen: "Yes",
                allergies: "Penicillin",
            },
        },
        {
            value: "clientTwo",
            label: "John Smith",
            profile: {
                address: "456 East Main Street",
                zip: "14618",
                city: "Brighton",
                state: "NY",
                typeOfResidence: "Apartment",
                primaryPhone: "(585) 555-5678",
                emergencyContactName: "Sarah Smith",
                emergencyContactPhone: "(585) 555-8765",
                relationshipToClient: "Daughter",
            },
        },
        {
            value: "clientThree",
            label: "Emily Keller",
            profile: {
                address: "789 Winton Road",
                zip: "14623",
                city: "Henrietta",
                state: "NY",
                typeOfResidence: "Townhouse",
                primaryPhone: "(585) 555-9012",
            },
        },
        {
            value: "clientFour",
            label: "Bobbert Dole",
            profile: {
                address: "321 Ridge Road",
                zip: "14580",
                city: "Webster",
                state: "NY",
                typeOfResidence: "Condo",
                primaryPhone: "(585) 555-3456",
            },
        },
    ];

    // Find the selected client's profile
    const selectedClient = clients.find((client) => client.value === selectedClientValue);
    const profile = selectedClient?.profile;

    // Provide the form, passing in one default value for now to make sure this works
    const defaultValues: Partial<CreateRideFormValues> = {
        additionalRider: "No",
    };

    // Handle client selection changes
    function handleClientChange(clientValue: string) {
        setSelectedClientValue(clientValue);
    }

    //
    async function handleSubmit(values: CreateRideFormValues) {
        // TODO: API logic for sending values
        console.log(values); // Testing to see if values appear after submit
        toast.success("Ride Saved");
        setOpen(false);
    }

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                <Button variant="outline">New Ride</Button>
            </DialogTrigger>
            <DialogContent className="!max-w-[692px] w-[95vw] max-h-[90vh] overflow-y-auto scroll-smooth p-6">
                <DialogHeader className="mb-4">
                    <DialogTitle>Ride Form</DialogTitle>
                </DialogHeader>

                <Tabs defaultValue="ride-details">
                    <TabsList>
                        <TabsTrigger value="ride-details">Ride Details</TabsTrigger>
                        <TabsTrigger value="client-details">Client Details</TabsTrigger>
                    </TabsList>

                    {/* The forceMount and className properties were added by ai */}
                    {/* keeps the client selected after switching to and form the client details tab */}
                    <TabsContent
                        value="ride-details"
                        forceMount
                        className="data-[state=inactive]:hidden"
                    >
                        <CreateRideForm
                            defaultValues={defaultValues}
                            onSubmit={handleSubmit}
                            clients={clients}
                            onClientChange={handleClientChange}
                        />
                    </TabsContent>

                    {/* Making fields display as they would when the data is populated. */}
                    <TabsContent value="client-details">
                        <div className="grid  gap-x-8 gap-y-6 w-full pt-5">
                            <h6>(Populated from client profile)</h6>
                            <div className="space-y-2">
                                <Label htmlFor="street-address">Street Address</Label>
                                <Input
                                    id="street-address"
                                    value={profile?.address ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="address2">Address 2</Label>
                                <Input id="address2" value={profile?.address2 ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="zip">ZIP</Label>
                                <Input id="zip" value={profile?.zip ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="city">City</Label>
                                <Input id="city" value={profile?.city ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="state">State</Label>
                                <Input id="state" value={profile?.state ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="type-of-residence">Type of Residence</Label>
                                <Input
                                    id="type-of-residence"
                                    value={profile?.typeOfResidence ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="email-address">Email Address</Label>
                                <Input
                                    id="email-address"
                                    value={profile?.emailAddress ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="primary-phone">Primary Phone</Label>
                                <Input
                                    id="primary-phone"
                                    value={profile?.primaryPhone ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="secondary-phone">Secondary Phone</Label>
                                <Input
                                    id="secondary-phone"
                                    value={profile?.secondaryPhone ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="emergency-contact-name">
                                    Emergency Contact Name
                                </Label>
                                <Input
                                    id="emergency-contact-name"
                                    value={profile?.emergencyContactName ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="emergency-contact-phone">
                                    Emergency Contact Phone
                                </Label>
                                <Input
                                    id="emergency-contact-phone"
                                    value={profile?.emergencyContactPhone ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="relationship-to-client">
                                    Relationship to Client
                                </Label>
                                <Input
                                    id="relationship-to-client"
                                    value={profile?.relationshipToClient ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="mobility-assistance">Mobility Assistance</Label>
                                <Input
                                    id="mobility-assistance"
                                    value={profile?.mobilityAssistance ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="other-limitations">Other Limitations</Label>
                                <Input
                                    id="other-limitations"
                                    value={profile?.otherLimitations ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="vehicle-type-needed">Vehicle Type Needed</Label>
                                <Input
                                    id="vehicle-type-needed"
                                    value={profile?.vehicleTypeNeeded ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="service-animal">Service Animal</Label>
                                <Input
                                    id="service-animal"
                                    value={profile?.serviceAnimal ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="oxygen">Oxygen</Label>
                                <Input id="oxygen" value={profile?.oxygen ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="allergies">Allergies</Label>
                                <Input id="allergies" value={profile?.allergies ?? ""} disabled />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="pick-up-instructions">Pick Up Instructions</Label>
                                <Input
                                    id="pick-up-instructions"
                                    value={profile?.pickUpInstructions ?? ""}
                                    disabled
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="comments-from-profile">Comments from Profile</Label>
                                <Textarea
                                    id="comments-from-profile"
                                    value={profile?.commentsFromProfile ?? ""}
                                    disabled
                                />
                            </div>
                        </div>
                    </TabsContent>
                </Tabs>

                <DialogFooter className="flex flex-row justify-end gap-3 mt-3">
                    <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                        Cancel
                    </Button>
                    <Button type="submit" form="create-ride-form">
                        Save
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
