name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'
      
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci --only=production && npm ci
      
      - name: Lint
        working-directory: ./server
        run: npm run lint
      
      - name: Check formatting
        working-directory: ./server
        run: npm run format:check
      
      - name: Start test services
        run: |
          docker compose up -d postgres
          sleep 10

      - name: Generate migrations
        working-directory: ./server
        run: |
          npx drizzle-kit generate --config ./drizzle.sys.config.ts
          npx drizzle-kit generate --config ./drizzle.org.config.ts

      - name: Run migrations
        working-directory: ./server
        run: tsx ./drizzle/migrate.ts
        env:
          SYS_DATABASE_URL: postgresql://braaaaam:password@localhost:5432/sys
          ORG_DATABASE_URL: postgresql://braaaaam:password@localhost:5432/org
      
      - name: Stop test services
        if: always()
        run: docker compose down